"""Init

Revision ID: 86e8f8e976dc
Revises: 
Create Date: 2022-12-09 20:09:01.505053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e8f8e976dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('NameModel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('obifka', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('power', sa.String(), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_table('model_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelID', sa.Integer(), nullable=True),
    sa.Column('clientID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clientID'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['modelID'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_clients_id'), 'model_clients', ['id'], unique=False)
    op.create_table('provider_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelID', sa.Integer(), nullable=True),
    sa.Column('providerID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modelID'], ['models.id'], ),
    sa.ForeignKeyConstraint(['providerID'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_models_id'), 'provider_models', ['id'], unique=False)
    op.create_table('valuables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release', sa.DateTime(), nullable=True),
    sa.Column('valuables', sa.String(), nullable=True),
    sa.Column('preparation', sa.String(), nullable=True),
    sa.Column('costs', sa.String(), nullable=True),
    sa.Column('modelID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modelID'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuables_id'), 'valuables', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuables_id'), table_name='valuables')
    op.drop_table('valuables')
    op.drop_index(op.f('ix_provider_models_id'), table_name='provider_models')
    op.drop_table('provider_models')
    op.drop_index(op.f('ix_model_clients_id'), table_name='model_clients')
    op.drop_table('model_clients')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
